"""Added google_sheet_id column

Revision ID: f8aadecc6094
Revises: c3dbb5087859
Create Date: 2025-07-23 02:23:30.787282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8aadecc6094'
down_revision = 'c3dbb5087859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_credentials', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('google_credentials')

    # ### end Alembic commands ###
